### Register
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "full_name": "chandra",
    "mobile": "082108210821",
    "location_id": 1,
    "gender": "Laki-Laki",
    "password": "password123",
    "is_admin": false
}

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "user_id": "000002",
    "password": "password123"
}

### Authenticated
GET http://localhost:3000/api/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMiIsImZ1bGxfbmFtZSI6Ik5hdXJhIFp1bCIsIm1vYmlsZSI6IjYyNDk1NDUxNTQ0OCIsInBhc3N3b3JkIjoicGFzc3dvcmQxMjMiLCJsb2NhdGlvbl9pZCI6MiwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMjI3MjMyMH0.PEYUAQ2w4SzFPG3d24mNJdG5s6TX8ugX-aEKAcf0vn8

### Change Password
POST http://localhost:3000/api/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMiIsImZ1bGxfbmFtZSI6Ik5hdXJhIFp1bCIsIm1vYmlsZSI6IjYyNDk1NDUxNTQ0OCIsInBhc3N3b3JkIjoicGFzc3dvcmQxMjMiLCJsb2NhdGlvbl9pZCI6MiwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMjI3MjMyMH0.PEYUAQ2w4SzFPG3d24mNJdG5s6TX8ugX-aEKAcf0vn8
Content-Type: application/json

{
    "old_password":"login1234",
    "new_password":"login123",
    "confirm_new_password":"login123"
}


### create locations
POST http://localhost:3000/api/locations
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwNCIsImZ1bGxfbmFtZSI6ImhhbGltYWgiLCJtb2JpbGUiOiIwODIxMDgyMTA4MjEiLCJwYXNzd29yZCI6ImhhbGltYWgxMjMiLCJsb2NhdGlvbl9pZCI6MSwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMDU2MTEwM30.AVeNOZGSwsTYqMk4AR3o_xCJ4IY0gk1d1OYgVEoGKO4

{
    "name": "cetroo",
    "tags": ["meneer","batam center","poltek","global","mcd"]
}

### show Locations
GET http://localhost:3000/api/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwNCIsImZ1bGxfbmFtZSI6ImhhbGltYWgiLCJtb2JpbGUiOiIwODIxMDgyMTA4MjEiLCJwYXNzd29yZCI6ImhhbGltYWgxMjMiLCJsb2NhdGlvbl9pZCI6MSwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMDU2MTEwM30.AVeNOZGSwsTYqMk4AR3o_xCJ4IY0gk1d1OYgVEoGKO4

### show attendants
GET http://localhost:3000/api/attendants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwNCIsImZ1bGxfbmFtZSI6ImhhbGltYWgiLCJtb2JpbGUiOiIwODIxMDgyMTA4MjEiLCJwYXNzd29yZCI6ImhhbGltYWgxMjMiLCJsb2NhdGlvbl9pZCI6MSwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMDU2MTEwM30.AVeNOZGSwsTYqMk4AR3o_xCJ4IY0gk1d1OYgVEoGKO4

### show attendant detail
GET http://localhost:3000/api/attendants/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwNCIsImZ1bGxfbmFtZSI6ImhhbGltYWgiLCJtb2JpbGUiOiIwODIxMDgyMTA4MjEiLCJwYXNzd29yZCI6ImhhbGltYWgxMjMiLCJsb2NhdGlvbl9pZCI6MSwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMDU2MTEwM30.AVeNOZGSwsTYqMk4AR3o_xCJ4IY0gk1d1OYgVEoGKO4

### show transactions
GET http://localhost:3000/api/attendants/1/analytics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwNCIsImZ1bGxfbmFtZSI6ImhhbGltYWgiLCJtb2JpbGUiOiIwODIxMDgyMTA4MjEiLCJwYXNzd29yZCI6ImhhbGltYWgxMjMiLCJsb2NhdGlvbl9pZCI6MSwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMDU2MTEwM30.AVeNOZGSwsTYqMk4AR3o_xCJ4IY0gk1d1OYgVEoGKO4
