openapi: 3.0.0
info:
  title: Fast Parking System
  description: Aplikasi Mobile
  version: 1.0.0

servers:
  - url: https://fast-parking-dev-api.up.railway.app/api
    description: Production server
  - url: http://localhost:3000/api
    description: Local server

paths:
  /register:
    post:
      summary: Register
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRegisterRequest"
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/AuthRegisterResponse"
  /login:
    post:
      summary: Login
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthLoginRequest"
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/AuthLoginResponse"
  /whoami:
    get:
      summary: Get Profile
      tags:
        - Auth
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/AuthWhoAmIResponse"
      security:
        - bearerAuth: []
  /attendants:
    get:
      summary: Get Attendants
      tags:
        - Attendants
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: location_id
          schema:
            type: number
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/GetAttendantsResponse"
      security:
        - bearerAuth: []
  /locations:
    post:
      summary: Add Location
      tags:
        - Locations
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLocationRequest"
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/AuthWhoAmIResponse"
      security:
        - bearerAuth: []
    get:
      summary: Get Locations
      tags:
        - Locations
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/GetLocationResponse"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    BasicResponse:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: "OK"
        error:
          type: object
          example: null
    AuthRegisterRequest:
      type: object
      properties:
        full_name:
          type: string
        mobile:
          type: string
        location_id:
          type: integer
        gender:
          type: string
          enum:
            - Laki-Laki
            - Perempuan
        password:
          type: string
        is_admin:
          type: boolean
    AuthRegisterResponse:
      type: object
      properties:
        user_id:
          type: string
          example: "000001"
    AuthLoginRequest:
      type: object
      properties:
        user_id:
          type: string
          example: "000004"
        password:
          type: string
          example: halimah123
    AuthLoginResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwNCIsImZ1bGxfbmFtZSI6ImhhbGltYWgiLCJtb2JpbGUiOiIwODIxMDgyMTA4MjEiLCJwYXNzd29yZCI6ImhhbGltYWgxMjMiLCJsb2NhdGlvbl9pZCI6MSwiZ2VuZGVyIjoiUGVyZW1wdWFuIiwiaXNfYWRtaW4iOjAsImlhdCI6MTcwMTQxNTU5OH0.EQrlP3ULsmHz-n_v3zgYFyADah2DOrCaNxqihGctgdE
        is_admin:
          type: boolean
          example: 0
    AuthWhoAmIResponse:
      type: object
      properties:
        id:
          type: string
          example: "000004"
        full_name:
          type: string
          example: "halimah"
        mobile:
          type: string
          example: "082108210821"
        password:
          type: string
          example: "halimah123"
        location_id:
          type: integer
          example: 1
        gender:
          type: string
          example: "Perempuan"
        is_admin:
          type: integer
          example: 0
    GetAttendantsResponse:
      type: object
      properties:
        id:
          type: string
          example: "000001"
        full_name:
          type: string
          example: naura
        location:
          type: string
          example: bengkong
        qr_code:
          type: string
          example: iVBORw0KGgoAAAANSUhEUgAAALkAAAC5CAAAAABRxsGAAAABvUlEQVR42u3cQRLCIAwF0N7/0rp3BH+gVimPlTO08lw0hEA9Hqu2g5ycnJycnJycnJycnPwu8uNze3fHy73BNw+ORk5O3g46fVYT8+6SqdHIyclLozevawaYqW8hJycP5MHFfQw5OfklsSWd38nJyU+SB7+rOasH6J+tLMjJl5cHVacTP11cnSMnX1keb9WMVZz/YIeLnHxlefDcz5StBscgJyf/kIaXJu9+NtHvGM3Pycm3kfdXwYEtXVAP5gbk5ORTda90T3e0+EVOvrW8H0L6kaJ+b7osJycnTx70PjpI4YOOk3a4yMl3kAcVq1LHdLWanHxbefp4p0EnzfxL95KTbytP93XSyvQAayYqkpNvI6+fTezn9qUK9mh+Tk6+gzz9FCTf9Qh10ikRcvKbywPg4Kr6i/k5Ofk28nQ+LhWW0zl/9G0FcvKby9M2s3gOwhQ5Ofn8f6DVi1X1FwTIyckfdUx6Wj89Q9FMAcjJyQfy89pI/7SyICffRp7uBKXxaz4/JycnT/P40u7udVVocvJ7yOu9QSk6OGxFTk4+X+Oqh5C099vVOXLyleVLNHJycnJycnJycnJycvIV2xPrUadYVBZzOQAAAABJRU5ErkJggg==
    CreateLocationRequest:
      type: object
      properties:
        name:
          type: string
          example: Politeknik Negeri Batam
        tags:
          type: array
          items:
            type: string
            example: Polibatam
    GetLocationResponse:
      type: object
      properties:
        name:
          type: string
          example: Politeknik Negeri Batam
        tags:
          type: array
          items:
            type: string
            example: Polibatam
